# Generated by Django 3.2.3 on 2021-05-27 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('max_way', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='product',
            new_name='products',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='amount',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='price',
            new_name='total_price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='combo',
        ),
        migrations.AddField(
            model_name='category',
            name='combo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='foods',
            field=models.ManyToManyField(related_name='_max_way_product_foods_+', to='max_way.Product'),
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(default='dsdsds'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Combo',
        ),
    ]
