# Generated by Django 3.2.3 on 2021-06-02 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('max_way', '0003_auto_20210602_1211'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='category',
        ),
    ]
