# Generated by Django 3.2.3 on 2021-06-23 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('max_way', '0006_bot_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='name_ru',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='description_ru',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='title',
            new_name='title_ru',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='address',
            new_name='address_ru',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='first_name',
            new_name='first_name_ru',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='last_name',
            new_name='first_name_uz',
        ),
        migrations.AddField(
            model_name='category',
            name='name_uz',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='description_uz',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='title_uz',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='address_uz',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='last_name_ru',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='last_name_uz',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
