# Generated by Django 3.2.3 on 2021-06-23 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('max_way', '0007_auto_20210623_0535'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name_ru',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='description_ru',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='title_ru',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='address_ru',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='first_name_ru',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='first_name_uz',
            new_name='last_name',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_uz',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description_uz',
        ),
        migrations.RemoveField(
            model_name='product',
            name='title_uz',
        ),
        migrations.RemoveField(
            model_name='user',
            name='address_uz',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name_ru',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name_uz',
        ),
    ]
