# Generated by Django 3.2.3 on 2021-06-23 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('max_way', '0008_auto_20210623_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bot_user',
            name='lang_id',
        ),
    ]
