# Generated by Django 3.2.3 on 2021-06-23 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('max_way', '0009_remove_bot_user_lang_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bot_user',
            table='bot_user',
        ),
    ]
