# Generated by Django 3.2.4 on 2021-06-24 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('max_way', '0011_alter_bot_user_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='chat_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
